<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>preview</LangVersion>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <AllowedReferenceRelatedFileExtensions>none</AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SelfContained)'=='true'">
    <PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Collections.Pooled" Version="2.0.0-preview.27" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="DotNetProjects.Extended.Wpf.Toolkit" Version="5.0.124" />
    <PackageReference Include="GitInfo" Version="3.3.5" />
    <PackageReference Include="gong-wpf-dragdrop" Version="4.0.0" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.7" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Onova" Version="2.6.13" />
    <PackageReference Include="System.Data.SQLite.Core" Version="1.0.119" />
    <PackageReference Include="WPFLocalizeExtension" Version="3.10.0" />
    <PackageReference Include="ZLinq" Version="1.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LibX4\LibX4.csproj" />
    <ProjectReference Include="..\X4_ComplexCalculator_CustomControlLibrary\X4_ComplexCalculator_CustomControlLibrary.csproj" />
    <ProjectReference Include="..\X4_DataExporterWPF\X4_DataExporterWPF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Common\Controls\DataGridFilters\MultiList\MultiListFilter.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Common\Dialogs\SelectStringDialog\SelectStringDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Main\Menu\File\Importers\LoadoutImporters\SelectLoadoutDialog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Localizations\Lang.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Localizations\Lang.en-US.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Localizations\Lang.ja-JP.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Common\Controls\DataGridFilters\MultiList\MultiListFilter.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Common\Dialogs\SelectStringDialog\SelectStringDialog.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Main\Menu\File\Importers\LoadoutImporters\SelectLoadoutDialog.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
