name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    if: >
      github.event_name == 'push' ||
      github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        Configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .Net Core 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x.x

      - name: Clean
        run: dotnet clean X4_ComplexCalculator.sln --configuration ${{ matrix.Configuration }} && dotnet nuget locals all --clear

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c ${{ matrix.Configuration }} --no-restore

      - name: Test
        run: dotnet test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: X4_ComplexCalculator-${{ matrix.Configuration }}-${{ github.sha }}
          path: X4_ComplexCalculator/bin/${{ matrix.Configuration }}/net6.0-windows
